version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: SixLabors.ImageSharp.Drawing
    versions:
    - "> 1.0.0.pre.beta11, < 1.1"
