version: 1.0.{build}
skip_branch_with_pr: true
build_script:
- cmd: dotnet publish --configuration Release
test_script:
- cmd: dotnet test TileService.Tests
artifacts:
- path: TileService\bin\Release\netcoreapp2.2\publish
